Name: product-api
Host: 127.0.0.1
Port: 8888

# 数据库连接配置
DataSource: root:darling1224@tcp(127.0.0.1:3306)/wmss?charset=utf8mb4&parseTime=true&loc=Local

# Redis 缓存（如暂时不用，可省略）
#CacheRedis:
#  - Host: 127.0.0.1:6379
#    Type: node
